DROP TABLE IF EXISTS income;
DROP TABLE IF EXISTS expense;

CREATE TABLE income (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value REAL NOT NULL
);

CREATE TABLE expense (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value REAL NOT NULL
);